name: "compile with emscripten"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: emscripten-core/setup-emsdk@v15

      - name: Verify
        run: emcc -v
  compile:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          repository: DuckDood/fpeeee
      - run: |
          ls
          emmake make -f Makefile_emscripten
